/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_jiangwei_JniTest */

#ifndef _Included_com_jiangwei_JniTest
#define _Included_com_jiangwei_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jiangwei_JniTest
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jiangwei_JniTest_getStringFromC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
